## Numpy: Package for Multidimentional array
### Vector(1D)
### Martix(2D or 1D)

In [2]:
import numpy as np

##### Create an Array

In [3]:
simple_list = [2,3,4]
np.array(simple_list)

array([2, 3, 4])

In [4]:
arr = np.array([5,6,7])
arr

array([5, 6, 7])

In [12]:
list_of_lists=[11,12,13],[21,22,23],[31,32,33]
print(list_of_lists)
print(type(list_of_lists))
np.array(list_of_lists)

([11, 12, 13], [21, 22, 23], [31, 32, 33])
<class 'tuple'>


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
np.arange(7,42)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41])

In [10]:
np.arange(3,31,4)

array([ 3,  7, 11, 15, 19, 23, 27])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(7,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [17]:
np.linspace(0,21,7)

array([ 0. ,  3.5,  7. , 10.5, 14. , 17.5, 21. ])

In [18]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3,5)

array([[0.51852004, 0.54070294, 0.60674993, 0.89066291, 0.01430447],
       [0.47963114, 0.07583095, 0.05228958, 0.62099591, 0.15180987],
       [0.99629599, 0.44679557, 0.8784951 , 0.62984575, 0.08923499]])

In [21]:
np.random.randn(3,5)

array([[ 0.70892304,  0.34372584,  1.47354346, -0.30481955, -0.21422768],
       [-1.90354719,  0.25150872, -1.78349969,  0.05076125,  0.21744255],
       [-1.13279992,  1.56819455,  0.31952714,  0.55091208,  0.89155132]])

In [22]:
np.random.randint(0,9,16)

array([5, 1, 2, 4, 8, 6, 4, 4, 8, 5, 4, 5, 7, 5, 1, 2])